services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    stop_grace_period: 2s
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
    volumes:
      - ./:/var/www/html
